# This is a basic workflow to help you get started with Actions

name: Test CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request_target:
    types: [opened, synchronize]
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-name:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Get Change Paths

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '3'
          path: ${GITHUB_WORKSPACE}/github.com/guguchecken/matrixone-test
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          go-version: 1.18
#           go-version-file: ${GITHUB_WORKSPACE}/github.com/guguchecken/matrixone-test/go.mod
      - name: Get PR Changed Paths
        uses: guguducken/change-paths-action@master
        id: ut-pr
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
      - name: Print Paths
        run: |
          ls ${GITHUB_WORKSPACE}
          export GO111MODULE=on
          test_scope=${{ steps.ut-pr.outputs.paths }}
          CGO_CFLAGS="-I${GITHUB_WORKSPACE}/github.com/guguchecken/matrixone-test/cgo" CGO_LDFLAGS="-L${GITHUB_WORKSPACE}/github.com/guguchecken/matrixone-test/cgo -lmo" go test -v -cover -run ^Test ${test_scope}
